---
- name: Disable logging in with passwords
  become: yes
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: PasswordAuthentication no
    state: present
    regexp: ^PasswordAuthentication
  notify: Restart ssh daemon

- name: Disable logging in as root
  become: yes
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: PermitRootLogin no
    state: present
    regexp: ^PermitRootLogin
  notify: Restart ssh daemon
