ALTER TABLE account
ALTER COLUMN name SET NOT NULL,
ALTER COLUMN email_address SET NOT NULL,
ALTER COLUMN first_login_at SET NOT NULL,
ALTER COLUMN last_login_at SET NOT NULL;

ALTER TABLE google_account
ALTER COLUMN google_account_id SET NOT NULL;

ALTER TABLE quiz
ALTER COLUMN name SET NOT NULL,
ALTER COLUMN deadline SET NOT NULL,
ALTER COLUMN external_id SET NOT NULL;

ALTER TABLE video
ALTER COLUMN url SET NOT NULL;
