---
- name: Create Dokku apps
  command: dokku apps:create {{ item.name }}
  args:
    creates: /home/dokku/{{ item.name }}
  with_items: "{{ apps }}"
- name: Configure nginx for static apps
  command: dokku config:set --no-restart {{ item.name }} NGINX_ROOT=dist
  when: item.static
  with_items: "{{ apps }}"
- name: Configure ports
  command: dokku proxy:ports-add {{ item.name }} http:{{ item.target_port }}:{{ item.container_port }}
  with_items: "{{ apps }}"
- name: Initialize repositories for static apps
  command: dokku git:initialize {{ item.name }}
  args:
    creates: /home/dokku/{{ item.name }}/branches
  when: item.static
  with_items: "{{ apps }}"
- name: Set environment variables
  command: dokku config:set --no-restart {{ item.app }} {{ item.name }}={{ item.value }}
  with_items: "{{ public_environment_variables + secret_environment_variables }}"
- name: Restart apps
  command: dokku ps:restart {{ item.name }}
  with_items: "{{ apps }}"
