---
- name: Download Dokku bootstrap script
  get_url:
    dest: /tmp
    url: https://raw.githubusercontent.com/dokku/dokku/{{ dokku_version }}/bootstrap.sh
- name: Execute bootstrap script
  environment:
    DOKKU_TAG: "{{ dokku_version }}"
    DOKKU_VHOST_ENABLE: "True"
    DOKKU_WEB_CONFIG: "False"
    DOKKU_HOSTNAME: "{{ inventory_hostname }}"
    DOKKU_SKIP_KEY_FILE: "True"
    DOKKU_KEY_FILE: ""
  become: yes
  command: bash bootstrap.sh
  args:
    chdir: /tmp
    creates: /home/dokku
