#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE "top10-dev";
    GRANT ALL PRIVILEGES ON DATABASE "top10-dev" TO "$POSTGRES_USER";

    CREATE DATABASE "top10-test";
    GRANT ALL PRIVILEGES ON DATABASE "top10-test" TO "$POSTGRES_USER";
EOSQL
